### ISSUE TITLE
Missing libcaer_driver.repos?

### ISSUE THREAD

**Issue by Huizerd** [ros-event-camera/libcaer_driver#2]
Hi, great work on the package! I managed to install on Ubuntu 22.04 with ROS2 Humble, but couldn't use the installation instructions given in the README. It seemed I needed the previously removed `libcaer_driver.repos`, but even after adding that manually the installation still complained about `camera_info_manager` and some others. I ended up using `rosdep`:
```
rosdep install --from-paths src -y --ignore-src
```
Which installed everything and then allowed me to build with `colcon` successfully. I was wondering if this is the way to go, or if there's another way to install dependencies automatically? I couldn't get any wiser from the CI build scripts either. Thanks!

**Comment by berndpfrommer** [comment]
Congratulations, you did everything right :)
Sorry, the build instructions are somewhat outdated. I now just refer to the standard ROS2 build instructions that I maintain elsewhere. And they use ... drum roll ... rosdep.
Thanks for the feedback!
I just pushed updated instructions, so closing this issue.
