### ISSUE TITLE
Python node can subscribe but doesn't receive messages

### ISSUE THREAD

**Issue by Huizerd** [ros-event-camera/libcaer_driver#3]
Hi, I'm trying to use these libraries to do inference with a live event camera (DVXplorer). The `libcaer_driver` node runs, receives the camera events, and I can visualize the events using `event_camera_renderer` by remapping `/event_camera/events` to `/renderer/events`. Now I'm looking to use the events in a Python node:
```python
import rclpy
from rclpy.node import Node
# from rclpy.qos import DurabilityPolicy, QoSProfile, ReliabilityPolicy

from event_camera_msgs.msg import EventPacket


class MinimalSubscriber(Node):
    def __init__(self):
        super().__init__("minimal_subscriber")
        self.subscription = self.create_subscription(EventPacket, "~/events", self.listener_callback, 10)
        # self.subscription = self.create_subscription(
        #     EventPacket,
        #     "~/events",
        #     self.listener_callback,
        #     QoSProfile(
        #         depth=1000,
        #         reliability=ReliabilityPolicy.RELIABLE,
        #         durability=DurabilityPolicy.VOLATILE,
        #     ),
        # )
        self.subscription  # prevent unused variable warning

    def listener_callback(self, msg):
        self.get_logger().info(str(msg.height))


def main(args=None):
    rclpy.init(args=args)
    minimal_subscriber = MinimalSubscriber()
    rclpy.spin(minimal_subscriber)
    minimal_subscriber.destroy_node()
    rclpy.shutdown()


if __name__ == "__main__":
    main()
```
Running the camera node like so:
```
ros2 run libcaer_driver driver_node --ros-args -p device_type:=dvxplorer
```
and running the subscriber like so:
```
ros2 run minimal minimal_subscriber --ros-args -r "~/events":="/libcaer_driver/events"
```
doesn't give any printing by the `listener_callback` however, even though `rqt_graph` shows they are connected:
![image](https://github.com/ros-event-camera/libcaer_driver/assets/15855769/bb7ad7ed-f26e-4a80-8ffe-1558f83a592b)

If I run `ros2 topic echo /libcaer_driver/events` I can see the messages, and if I publish manually to `/libcaer_driver/events` with `ros2 topic pub /libcaer_driver/events event_camera_msgs/msg/EventPacket` the `listener_callback` does get called and prints. Changing the QoS settings (commented) also didn't help.

Given all this, I suspect that there's something special about the C++ `libcaer_driver` node, but I haven't been able to find it. Could you be so kind to point me in the right direction? :)

**Comment by Huizerd** [comment]
Update: creating an equivalent `minimal_subscriber` node in C++ gives the same problems.

**Comment by Huizerd** [comment]
Never mind. I thought I copied the QoS settings correctly, but I put `ReliabilityPolicy.RELIABLE` instead of `ReliabilityPolicy.BEST_EFFORT`. Changing this makes it work. Closing this!

**Comment by berndpfrommer** [comment]
The QoS fairy has struck again ... sorry you wasted time on this. Hopefully people will see this issue when they hit the same snag.
